name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
      - run: echo "ğŸ‰ A tarefa foi disparada automaticamente por um evento $ {{github.event_name}}."
      - run: echo "ğŸ§ Este trabalho agora estÃ¡ sendo executado em um servidor $ {{runner.os}} hospedado pelo GitHub!"
      - run: echo "ğŸ” O nome do seu branch Ã© $ {{github.ref}} e seu repositÃ³rio Ã© $ {{github.repository}}."
      - nome: Verifique o cÃ³digo do repositÃ³rio
        usa: aÃ§Ãµes / checkout @ v2
      - run: echo "ğŸ’¡ O repositÃ³rio $ {{github.repository}} foi clonado para o runner."
      - run: echo "ğŸ–¥ï¸ O fluxo de trabalho agora estÃ¡ pronto para testar seu cÃ³digo no executor."
      - nome: lista os arquivos no repositÃ³rio
        correr: |
          ls $ {{github.workspace}}
      - run: echo "ğŸ O status deste trabalho Ã© $ {{job.status}}."
