name: Test

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Sistema
    runs-on: ubuntu-latest
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    -name: Set up Node
     uses: actions/setup-node@v1
     with:
      node-version: 12
    
    - name: Checkout repository
    - uses: actions/checkout@v2
    
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
        
    - name: Install depedencies
      run: yarn
      
    - name: Test
      run: yarn test --coverage

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
