name: Lint commit

on: pull_request

jobs:
  commit:
    name: Lint commit messages
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.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 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v1



